arb-dir: lib/l10n
template-arb-file: app_en.arb
output-localization-file: app_localizations.dart
untranslated-messages-file: lib/l10n/l10n_missing.txt
output-class: AppLocalizations
synthetic-package: true