// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3zOgApZCbOhVbvSrAA6BsxCq-lY9pC2A',
    appId: '1:445098151322:web:451c2401359a59df5e7e23',
    messagingSenderId: '445098151322',
    projectId: 'pim-msaware',
    authDomain: 'pim-msaware.firebaseapp.com',
    storageBucket: 'pim-msaware.firebasestorage.app',
    measurementId: 'G-TNEVRW9RM9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvCPjVj7609MWY_97yypb-nObxJwuUYDo',
    appId: '1:445098151322:android:6854f495c57b1f505e7e23',
    messagingSenderId: '445098151322',
    projectId: 'pim-msaware',
    storageBucket: 'pim-msaware.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcYEYXKIJz9Y9cu8PGDjzDAy9VyVBHCcA',
    appId: '1:445098151322:ios:3a44e521e634e0d95e7e23',
    messagingSenderId: '445098151322',
    projectId: 'pim-msaware',
    storageBucket: 'pim-msaware.firebasestorage.app',
    androidClientId: '445098151322-hfd4iglag9h5qhcokobhcut63th2jq4t.apps.googleusercontent.com',
    iosClientId: '445098151322-7cau61on645q0ao5fa3qjqnpefdl42nc.apps.googleusercontent.com',
    iosBundleId: 'com.example.pim',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAcYEYXKIJz9Y9cu8PGDjzDAy9VyVBHCcA',
    appId: '1:445098151322:ios:3a44e521e634e0d95e7e23',
    messagingSenderId: '445098151322',
    projectId: 'pim-msaware',
    storageBucket: 'pim-msaware.firebasestorage.app',
    androidClientId: '445098151322-hfd4iglag9h5qhcokobhcut63th2jq4t.apps.googleusercontent.com',
    iosClientId: '445098151322-7cau61on645q0ao5fa3qjqnpefdl42nc.apps.googleusercontent.com',
    iosBundleId: 'com.example.pim',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA3zOgApZCbOhVbvSrAA6BsxCq-lY9pC2A',
    appId: '1:445098151322:web:c997316bfa63ebc75e7e23',
    messagingSenderId: '445098151322',
    projectId: 'pim-msaware',
    authDomain: 'pim-msaware.firebaseapp.com',
    storageBucket: 'pim-msaware.firebasestorage.app',
    measurementId: 'G-FFEHR0H3WE',
  );
}
